export const products = [
  {
    id: 'solar1',
    name: {
      th: 'โซลาร์รูฟท็อป',
      en: 'Solar Rooftop',
    }, slug: 'solar-rooftop',
    brands: [
      {
        id: 'brand1',
        name: 'HUAWEI',
        slug: 'huawei',
        brandImage: '/brands/logo-Huawei.png',
        types: ['Premium', 'Standard', 'Hybrid'],
        packages: [
          {
            id: 'pkg1',
            name: 'ชุดแพ็คเกจโซลาร์รูฟท็อป [HUAWEI]',
            type: 'Standard',
            items: [
              {
                id: 'item1',
                inverter_model: 'SUN2000-3KTL-L1',
                size: '1.8 kW',
                power_system: '1 เฟส',
                panel_count: 3,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 99000,
                battery: '',
                area: '9 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item1-1.jpg',
                  '/images/solar1/item1-2.jpg',
                  '/images/solar1/item1-3.jpg',
                ],
              },
              {
                id: 'item2',
                inverter_model: 'SUN2000-10KTL-LC0',
                size: '3.1 kW',
                power_system: '1 เฟส',
                panel_count: 5,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 128000,
                battery: '',
                area: '14 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item2-1.jpg',
                  '/images/solar1/item2-2.jpg',
                ],
              },
              {
                id: 'item3',
                inverter_model: 'SUN2000-10KTL-LC0',
                size: '5 kW',
                power_system: '1 เฟส',
                panel_count: 8,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 170000,
                battery: '',
                area: '23 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item2-1.jpg',
                  '/images/solar1/item2-2.jpg',
                ],
              },
              {
                id: 'item4',
                inverter_model: 'SUN2000-10KTL-LC0',
                size: '5 kW',
                power_system: '3 เฟส',
                panel_count: 8,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 181000,
                battery: '',
                area: '23 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item2-1.jpg',
                  '/images/solar1/item2-2.jpg',
                ],
              },
              {
                id: 'item5',
                inverter_model: 'SUN2000-10KTL-LC0',
                size: '10 kW',
                power_system: '1 เฟส',
                panel_count: 16,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 243000,
                battery: '',
                area: '45 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item2-1.jpg',
                  '/images/solar1/item2-2.jpg',
                ],
              },
              {
                id: 'item6',
                inverter_model: 'SUN2000-10KTL-LC0',
                size: '10 kW',
                power_system: '3 เฟส',
                panel_count: 16,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 262000,
                battery: '',
                area: '45 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item2-1.jpg',
                  '/images/solar1/item2-2.jpg',
                ],
              },
              {
                id: 'item7',
                inverter_model: 'SUN2000-10KTL-LC0',
                size: '15 kW',
                power_system: '3 เฟส',
                panel_count: 24,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 380000,
                battery: '',
                area: '68 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item2-1.jpg',
                  '/images/solar1/item2-2.jpg',
                ],
              },
              {
                id: 'item8',
                inverter_model: 'SUN2000-10KTL-LC0',
                size: '20 kW',
                power_system: '3 เฟส',
                panel_count: 32,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 470000,
                battery: '',
                area: '90 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item2-1.jpg',
                  '/images/solar1/item2-2.jpg',
                ],
              },
              {
                id: 'item9',
                inverter_model: 'SUN2000-10KTL-LC0',
                size: '25 kW',
                power_system: '3 เฟส',
                panel_count: 40,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 630000,
                battery: '',
                area: '112 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item2-1.jpg',
                  '/images/solar1/item2-2.jpg',
                ],
              },
              {
                id: 'item10',
                inverter_model: 'SUN2000-10KTL-LC0',
                size: '30 kW',
                power_system: '3 เฟส',
                panel_count: 48,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 710000,
                battery: '',
                area: '135 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item2-1.jpg',
                  '/images/solar1/item2-2.jpg',
                ],
              },
              {
                id: 'item11',
                inverter_model: 'SUN2000-10KTL-LC0',
                size: '35 kW',
                power_system: '3 เฟส',
                panel_count: 56,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 809000,
                battery: '',
                area: '157 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item2-1.jpg',
                  '/images/solar1/item2-2.jpg',
                ],
              },
              {
                id: 'item12',
                inverter_model: 'SUN2000-10KTL-LC0',
                size: '40 kW',
                power_system: '3 เฟส',
                panel_count: 64,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 906000,
                battery: '',
                area: '179 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item2-1.jpg',
                  '/images/solar1/item2-2.jpg',
                ],
              },
              // ... รายการ items อื่น ๆ ของ HUAWEI pkg1
            ],
          },
          // ถ้ามี package อื่นของ HUAWEI ก็เพิ่มที่นี่
        ],
      },
      {
        id: 'brand2',
        name: 'GROWATT',
        slug: 'growatt',
        brandImage: '/brands/logo-Growatt.png',
        types: ['Premium', 'Standard'],
        packages: [
          {
            id: 'pkg2',
            name: 'ชุดแพ็คเกจโซลาร์รูฟท็อป [Growatt]',
            type: 'Standard',
            items: [
              {
                id: 'item13',
                inverter_model: 'Growatt Min 3000 TL-X',
                size: '1.8 kW',
                power_system: '1 เฟส',
                panel_count: 3,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 97000,
                battery: '',
                area: '9 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item4-1.jpg',
                  '/images/solar1/item4-2.jpg',
                ],
              },
              {
                id: 'item14',
                inverter_model: 'Growatt Min 3000 TL-X',
                size: '3.1 kW',
                power_system: '1 เฟส',
                panel_count: 5,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 125000,
                battery: '',
                area: '14 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item4-1.jpg',
                  '/images/solar1/item4-2.jpg',
                ],
              },
              {
                id: 'item15',
                inverter_model: 'Growatt Min 3000 TL-X',
                size: '5 kW',
                power_system: '1 เฟส',
                panel_count: 8,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 168000,
                battery: '',
                area: '23 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item4-1.jpg',
                  '/images/solar1/item4-2.jpg',
                ],
              },

              {
                id: 'item16',
                inverter_model: 'Growatt Min 3000 TL-X',
                size: '5 kW',
                power_system: '3 เฟส',
                panel_count: 8,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 190000,
                battery: '',
                area: '23 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item4-1.jpg',
                  '/images/solar1/item4-2.jpg',
                ],
              },

              {
                id: 'item17',
                inverter_model: 'Growatt Min 3000 TL-X',
                size: '10 kW',
                power_system: '3 เฟส',
                panel_count: 16,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 252000,
                battery: '',
                area: '45 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item4-1.jpg',
                  '/images/solar1/item4-2.jpg',
                ],
              },
              {
                id: 'item18',
                inverter_model: 'Growatt Min 3000 TL-X',
                size: '15 kW',
                power_system: '3 เฟส',
                panel_count: 24,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 391000,
                battery: '',
                area: '68 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item4-1.jpg',
                  '/images/solar1/item4-2.jpg',
                ],
              },

              {
                id: 'item19',
                inverter_model: 'Growatt Min 3000 TL-X',
                size: '20 kW',
                power_system: '3 เฟส',
                panel_count: 32,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 476000,
                battery: '',
                area: '90 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item4-1.jpg',
                  '/images/solar1/item4-2.jpg',
                ],
              },
              {
                id: 'item20',
                inverter_model: 'Growatt Min 3000 TL-X',
                size: '30 kW',
                power_system: '3 เฟส',
                panel_count: 48,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 708000,
                battery: '',
                area: '135 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item4-1.jpg',
                  '/images/solar1/item4-2.jpg',
                ],
              },
              {
                id: 'item21',
                inverter_model: 'Growatt Min 3000 TL-X',
                size: '35 kW',
                power_system: '3 เฟส',
                panel_count: 56,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 795000,
                battery: '',
                area: '157 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item4-1.jpg',
                  '/images/solar1/item4-2.jpg',
                ],
              },
              {
                id: 'item22',
                inverter_model: 'Growatt Min 3000 TL-X',
                size: '40 kW',
                power_system: '3 เฟส',
                panel_count: 64,
                panel_type: 'Longi Hi-Mo7 (625 Watt)',
                price: 880000,
                battery: '',
                area: '179 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item4-1.jpg',
                  '/images/solar1/item4-2.jpg',
                ],
              },
              // เพิ่ม items อื่น ๆ ของแพ็คเกจนี้ได้
            ],
          },
          // package อื่นของ GROWATT ถ้ามี
        ],
      },
    ],
  },
  {
    id: 'solar2',
    name: {
      th: 'โซลาร์รูฟท็อปไฮบริด',
      en: 'Solar Rooftop Hybrid',
    },
    slug: 'solar-rooftop-hybrid',
    brands: [
      {
        id: 'brand1-hybrid',
        name: 'DEYE',
        slug: 'deye',
        brandImage: '/brands/logo-Huawei.png',
        types: ['Hybrid'],
        packages: [
          {
            id: 'pkg-huawei-hybrid-01',
            name: 'ชุดแพ็คเกจโซลาร์รูฟท็อป ไฮบริด [HUAWEI]',
            type: 'Hybrid',
            items: [
              {
                id: 'item23',
                inverter_model: 'SUN-10K-SG05LP1-EU',
                size: '5 kW',
                power_system: '1 เฟส',
                panel_count: 8,
                panel_type: '',
                price: 209000,
                battery: 'แบตเตอรี่ 5.2 kWh',
                area: '23 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item3-1.jpg',
                  '/images/solar1/item3-2.jpg',
                ],
              },
              {
                id: 'item24',
                inverter_model: 'SUN-5K-SG04LP3-EU',
                size: '5 kW',
                power_system: '1 เฟส',
                panel_count: 8,
                panel_type: '',
                price: 241000,
                battery: 'แบตเตอรี่ 5.2 kWh',
                area: '23 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item3-1.jpg',
                  '/images/solar1/item3-2.jpg',
                ],
              },
              {
                id: 'item25',
                inverter_model: 'SUN-10K-SG04LP3-EU',
                size: '10 kW',
                power_system: '3 เฟส',
                panel_count: 16,
                panel_type: '',
                price: 319000,
                battery: 'แบตเตอรี่ 5.2 kWh',
                area: '45 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item3-1.jpg',
                  '/images/solar1/item3-2.jpg',
                ],
              },
              {
                id: 'item26',
                inverter_model: 'SUN-15K-SG05LP3-EU-SM2',
                size: '15 kW',
                power_system: '3 เฟส',
                panel_count: 24,
                panel_type: '',
                price: 441000,
                battery: 'แบตเตอรี่ 5.2 kWh',
                area: '68 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item3-1.jpg',
                  '/images/solar1/item3-2.jpg',
                ],
              },
              {
                id: 'item27',
                inverter_model: 'SUN-10K-SG05LP1-EU',
                size: '10 kW',
                power_system: '1 เฟส',
                panel_count: 16,
                panel_type: '',
                price: 340000,
                battery: 'แบตเตอรี่ 10.7 kWh',
                area: '45 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item3-1.jpg',
                  '/images/solar1/item3-2.jpg',
                ],
              },
              {
                id: 'item28',
                inverter_model: 'SUN-15K-SG05LP3-EU-SM2',
                size: '15 kW',
                power_system: '3 เฟส',
                panel_count: 24,
                panel_type: '',
                price: 475000,
                battery: 'แบตเตอรี่ 10.7 kWh',
                area: '68 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item3-1.jpg',
                  '/images/solar1/item3-2.jpg',
                ],
              },
              {
                id: 'item29',
                inverter_model: 'SUN-15K-SG05LP3-EU-SM2',
                size: '15 kW',
                power_system: '3 เฟส',
                panel_count: 24,
                panel_type: '',
                price: 475000,
                battery: 'แบตเตอรี่ 15.97 kWh',
                area: '68 ตารางเมตร',
                mainImage: '/products/solar-rooftop-HUAWEI.jpg',
                gallery: [
                  '/images/solar1/item3-1.jpg',
                  '/images/solar1/item3-2.jpg',
                ],
              },

            ],
          },
        ],
      },
      {
        id: 'brand3-hybrid',
        name: 'Deye',
        slug: 'deye',
        brandImage: '/brands/logo-Huawei.png',
        types: ['Hybrid'],
        packages: [
          {
            id: 'pkg-deye-hybrid-01',
            name: 'ชุดแพ็คเกจโซลาร์รูฟท็อป ไฮบริด[HUAWEI]',
            type: 'Hybrid',
            items: [
              {
                id: 'item30',
                inverter_model: 'SUN2000-5KTL-L1',
                size: '5 kW',
                power_system: '1 เฟส',
                panel_count: 8,
                panel_type: '',
                price: 389000,
                battery: 'แบตเตอรี 7 kWh',
                area: '45 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },
              {
                id: 'item31',
                inverter_model: 'SUN2000-5KTL-MAPO',
                size: '5 kW',
                power_system: '3 เฟส',
                panel_count: 8,
                panel_type: '',
                price: 414000,
                battery: 'แบตเตอรี 7 kWh',
                area: '45 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },
              {
                id: 'item32',
                inverter_model: 'SUN2000-10KTL-LCO',
                size: '10 kW',
                power_system: '1 เฟส',
                panel_count: 16,
                panel_type: '',
                price: 459000,
                battery: 'แบตเตอรี 7 kWh',
                area: '68 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },
              {
                id: 'item33',
                inverter_model: 'SUN2000-10KTL-MAPO',
                size: '10 kW',
                power_system: '3 เฟส',
                panel_count: 16,
                panel_type: '',
                price: 459000,
                battery: 'แบตเตอรี 7 kWh',
                area: '68 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },
              {
                id: 'item34',
                inverter_model: 'SUN2000-15KTL-MB0',
                size: '15 kW',
                power_system: '3 เฟส',
                panel_count: 24,
                panel_type: '',
                price: 624000,
                battery: 'แบตเตอรี 7 kWh',
                area: '68 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },
              {
                id: 'item35',
                inverter_model: 'SUN2000-20KTL-MBO',
                size: '20 kW',
                power_system: '3 เฟส',
                panel_count: 32,
                panel_type: '',
                price: 720000,
                battery: 'แบตเตอรี 7 kWh',
                area: '68 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },
              {
                id: 'item36',
                inverter_model: 'SUN2000-10KTL-LCO',
                size: '10 kW',
                power_system: '1 เฟส',
                panel_count: 16,
                panel_type: '',
                price: 593000,
                battery: 'แบตเตอรี่ 14 kWh',
                area: '68 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },
              {
                id: 'item37',
                inverter_model: 'SUN2000-10KTL-MAPO',
                size: '10 kW',
                power_system: '3 เฟส',
                panel_count: 16,
                panel_type: '',
                price: 628000,
                battery: 'แบตเตอรี่ 14 kWh',
                area: '70 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },
              {
                id: 'item38',
                inverter_model: 'SUN2000-15KTL-MBO',
                size: '15 kW',
                power_system: '3 เฟส',
                panel_count: 24,
                panel_type: '',
                price: 759000,
                battery: 'แบตเตอรี่ 14 kWh',
                area: '59 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },
              {
                id: 'item39',
                inverter_model: 'SUN2000-15KTL-MBO',
                size: '15 kW',
                power_system: '3 เฟส',
                panel_count: 24,
                panel_type: '',
                price: 759000,
                battery: 'แบตเตอรี่ 14 kWh',
                area: '59 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },
              {
                id: 'item40',
                inverter_model: 'SUN2000-20KTL-MBO',
                size: '20 kW',
                power_system: '3 เฟส',
                panel_count: 32,
                panel_type: '',
                price: 849000,
                battery: 'แบตเตอรี่ 14 kWh',
                area: '96 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },
              {
                id: 'item41',
                inverter_model: 'HUAWEI SUN2000-20KTL-MB0',
                size: '20 kW',
                power_system: '3 เฟส',
                panel_count: 32,
                panel_type: '',
                price: 985000,
                battery: 'แบตเตอรี่ 21 kWh',
                area: '100 ตารางเมตร',
                mainImage: '/products/solar-rooftop-Growatt.jpg',
                gallery: [
                  '/images/solar1/item5-1.jpg',
                  '/images/solar1/item5-2.jpg',
                ],
              },

            ],
          },
        ],
      },
    ],
  },
  {
    id: 'solar3',
    name: {
      th: 'โซลาร์แอร์',
      en: 'Solar Air',
    }, slug: 'solar-air',
    brands: [
      {
        id: 'brand4',
        name: 'sincLair',
        slug: 'sinclair',
        brandImage: '/brands/logo-Sinclair.png',

        items: [
          {
            id: 'item42',
            model: 'SIHC09BIF/ SOHC - 09BIF',
            size: '9200 BTU',
            panel_type: 'Longi Hi-Mo 7 (625 Watt)',
            panel_count: 2,
            price: 38000,
            area: '6 ตารางเมตร',
            mainImage: '/products/solar-air.jpg',
            gallery: [
              '/images/solar2/item6-1.jpg',
              '/images/solar2/item6-2.jpg',
            ],
          },
          {
            id: 'ite43',
            model: 'SIHC-12BIF/ SOHC - 12BIF',
            size: '12,500 BTU',
            panel_type: 'Longi Hi-Mo 7 (625 Watt)',
            panel_count: 3,
            price: 45000,
            area: '9 ตารางเมตร',
            mainImage: '/products/solar-air.jpg',
            gallery: [
              '/images/solar2/item6-1.jpg',
              '/images/solar2/item6-2.jpg',
            ],
          },
          {
            id: 'item44',
            model: 'SIHC 24BIF/ SOHC - 24BIF',
            size: '22,000 BTU',
            panel_type: 'Longi Hi-Mo 7 (625 Watt)',
            panel_count: 5,
            price: 66000,
            area: '15 ตารางเมตร',
            mainImage: '/products/solar-air.jpg',
            gallery: [
              '/images/solar2/item7-1.jpg',
              '/images/solar2/item7-2.jpg',
            ],
          },
          {
            id: 'item45',
            model: 'SIHC 24BIF/ SOHC - 24BIF',
            size: '22,044 BTU',
            panel_type: 'Longi Hi-Mo 7 (625 Watt)',
            panel_count: 5,
            price: 66444,
            area: '15 ตารางเมตร',
            mainImage: '/products/solar-air.jpg',
            gallery: [
              '/images/solar2/item7-1.jpg',
              '/images/solar2/item7-2.jpg',
            ],
          },
        ],
      },
      {
        id: 'brand5',
        name: 'LONGi',
        slug: 'longi',
        brandImage: '/brands/logo-longi.png',

        items: [], // ยังไม่มีสินค้า air จากแบรนด์นี้
      },
    ],
  },

];
